:Author: ard12sgf1960
:Email: {AuthorEmail}
:Date: 24/11/2022
:Revision: version#
:License: Public Domain

== Project: {SerialToSerialBT}

This project connects to a Bluetooth device and sends and receives data.
It will use the received data to control the *_INBUILT_LED_*.

The code needs to receive text to control the LED.
Send "Led On", "Led Off", "Toggle" to the ESP32 to control the LED.

=== Boards: Verified Boards
This code works with:-

> ESP32 WROOM Development Module

> All other ESP32 Boards 

Some basic Git commands are:
```
git status

int LED_BUILTIN = 2;
```

=== Configurations:
The INBUILT attribute may be different on other boards.
The ESP32 WROOM uses the WiFi module to control on-board LEDS.
Ensure WifiNINA library is included.

=== Step 1: Code Installation
Upload the code to the ESP32 by connecting a USB cable between the device and Project.
When the PC is attempting to connect you may need to press the BOOT button a number of times.
Once the download starts the button can be released.

=== Step 2: Android App Installation
Load the Android App Serial Bluetooth App

=== Step 3: Configure the App
The app has a row of function buttons that you will need to reconfigure.

"[M1] [M2] [M3] [M4] [M5] [M6]"

Long press on a function key and change the attributes.

.Bluetooth Table 
[options="header,footer"]
|===
| Button | Name  | Value
| M1 | Led On  | Led On
| M2 | Led Off  | Led Off
| M3 | Toggle | Toggle
|===

=== Step 4: Function
Press the newly named function keys to send the data to the board.
The code will turn on and off the on-board LED and print to the monitor.

=== Step 5: Assemble the circuit

No assembly required

=== Folder structure
....
 SerialToSerialBT          => Arduino sketch folder
  |-SerialToSerialBT.ino   => main Arduino file
  |-ReadMe.adoc            => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact ard12sgf1960 https://id.arduino.cc/ard12sgf1960

=== BOM
Add the bill of the materials you need for this project.

.Bill of Materials
[options="header,footer"]
|===
| ID | Part name          | Part number | Quantity
| B1 | ESP32 TTGO Board   | 1234-abcd   | 1
| C1 | USB Type 3 Cable   | 2345-asdf   | 1
|===

=== Help
This document is written in the   , a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
